title: Usuarios
modelClass: AdrisonLuz\NanoConfig\Models\Usuario
list: $/adrisonluz/nanoconfig/models/usuario/columns.yaml
recordUrl: 'adrisonluz/nanoconfig/usuarios/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
